abstract class LocalizationKeys {
  static const YES = 'YES';
  static const NO = 'NO';
  static const PROCESS_RESULT = 'PROCESS_RESULT';
  static const PERSON_PERSON = 'PERSON.PERSON';
  static const DELETE_SUCCESS = 'DELETE_SUCCESS';
  static const DELETE_ERROR = 'DELETE_ERROR ';
  static const STAY_THIS_SCREEN = 'STAY_THIS_SCREEN';
  static const GO_LIST_SCREEN = 'GO_LIST_SCREEN';
  static const POSITION_UP = 'POSITION_UP';
  static const WRITE = 'WRITE';
  static const CHOOSE = 'CHOOSE';
  static const REQUIRED = 'REQUIRED ';

  //LOGIN
  static const LOGIN_USERNAME = "LOGIN.USERNAME";
  static const LOGIN_PASSWORD = 'LOGIN.PASSWORD';
  static const LOGIN_REMEMBER_ME = 'LOGIN.REMEMBER_ME';
  static const LOGIN_LOGIN = 'LOGIN.LOGIN';
  static const LOGIN_USERNAME_EMPTY = 'LOGIN.USERNAME_EMPTY';
  static const LOGIN_PASSWORD_EMPTY = 'LOGIN.PASSWORD_EMPTY';

// PERSON
  static const PERSON_IDENDITY = 'PERSON.IDENDITY';
  static const PERSON_IDENDITY_ERROR = 'PERSON.IDENDITY_ERROR';
  static const PERSON_NAME = 'PERSON.NAME';
  static const PERSON_SURNAME = 'PERSON.SURNAME';
  static const PERSON_NAME_SURNAME = 'PERSON.NAME_SURNAME';
  static const PERSON_SALLARY = 'PERSON.SALLARY';
  static const PERSON_COMPANY = 'PERSON.COMPANY';
  static const PERSON_JOB_TITLE = 'PERSON.JOB_TITLE';
  static const PERSON_JOB_DESCRIPTION = 'PERSON.JOB_DESCRIPTION';
  static const PERSON_BIRTH_DAY = 'PERSON.BIRTH_DAY';
  static const PERSON_PHONE_NUMBER = 'PERSON.PHONE_NUMBER';

  //PERSON_LIST_VIEW
  static const PERSON_LIST_VIEW_APP_BAR_TITLE =
      'PERSON_LIST_VIEW.APP_BAR_TITLE';
  static const PERSON_LIST_VIEW_FAB_BUTTON_UP =
      'PERSON_LIST_VIEW.FAB_BUTTON_UP';
  static const PERSON_LIST_VIEW_FAB_BUTTON_ADD_PERSON =
      'PERSON_LIST_VIEW.FAB_BUTTON_ADD_PERSON';
  static const PERSON_LIST_VIEW_PERSON_DELETE =
      'PERSON_LIST_VIEW.PERSON_DELETE';
  static const PERSON_LIST_VIEW_PERSON_DELETE_PROCESS =
      'PERSON_LIST_VIEW.PERSON_DELETE_PROCESS';
  static const PERSON_LIST_VIEW_PERSON_DELETE_PROCESS_SURE =
      'PERSON_LIST_VIEW.PERSON_DELETE_PROCESS_SURE';
  static const PERSON_LIST_VIEW_REFRESH = 'PERSON_LIST_VIEW.REFRESH';

// PERSON DETAIL VIEW
  static const PERSON_DETAIL_VIEW_ADD_PERSON = 'PERSON_DETAIL_VIEW.ADD_PERSON';
  static const PERSON_DETAIL_VIEW_ADD_PERSON_RESULT =
      'PERSON_DETAIL_VIEW.ADD_PERSON_RESULT';
  static const PERSON_DETAIL_VIEW_ADD_PERSON_RESULT_SUCCESS =
      'PERSON_DETAIL_VIEW.ADD_PERSON_RESULT_SUCCESS';
  static const PERSON_DETAIL_VIEW_ADD_PERSON_RESULT_ERROR =
      'PERSON_DETAIL_VIEW.ADD_PERSON_RESULT_ERROR';
  static const PERSON_DETAIL_VIEW_UPDATE_PERSON_RESULT =
      'PERSON_DETAIL_VIEW.UPDATE_PERSON_RESULT';
  static const PERSON_DETAIL_VIEW_UPDATE_PERSON_RESULT_SUCCESS =
      'PERSON_DETAIL_VIEW.UPDATE_PERSON_RESULT_SUCCESS';
  static const PERSON_DETAIL_VIEW_UPDATE_PERSON_RESULT_ERROR =
      'PERSON_DETAIL_VIEW.UPDATE_PERSON_RESULT_ERROR';
}
